### ISSUE TITLE
certs have expired

### ISSUE THREAD

**Issue by weisjohn** [nategood/node-auth#2]
Thanks for making this. Do you think you could take a look at this?

```
$ node client.js 

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: CERT_HAS_EXPIRED
    at SecurePair.<anonymous> (tls.js:1356:32)
    at SecurePair.EventEmitter.emit (events.js:92:17)
    at SecurePair.maybeInitFinished (tls.js:968:10)
    at CleartextStream.read [as _read] (tls.js:462:15)
    at CleartextStream.Readable.read (_stream_readable.js:320:10)
    at EncryptedStream.write [as _write] (tls.js:366:25)
    at doWrite (_stream_writable.js:221:10)
    at writeOrBuffer (_stream_writable.js:211:5)
    at EncryptedStream.Writable.write (_stream_writable.js:180:11)
    at write (_stream_readable.js:583:24)
```

**Comment by nategood** [comment]
Looks like my certs have expired.  I can create new ones this week.

On Tue, Nov 5, 2013 at 2:48 PM, John Weis notifications@github.com wrote:

> Thanks for making this. Do you think you could take a look at this?
> 
> $ node client.js
> 
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: CERT_HAS_EXPIRED
>     at SecurePair.<anonymous> (tls.js:1356:32)
>     at SecurePair.EventEmitter.emit (events.js:92:17)
>     at SecurePair.maybeInitFinished (tls.js:968:10)
>     at CleartextStream.read [as _read](tls.js:462:15)
>     at CleartextStream.Readable.read (_stream_readable.js:320:10)
>     at EncryptedStream.write [as _write](tls.js:366:25)
>     at doWrite (_stream_writable.js:221:10)
>     at writeOrBuffer (_stream_writable.js:211:5)
>     at EncryptedStream.Writable.write (_stream_writable.js:180:11)
>     at write (_stream_readable.js:583:24)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/nategood/node-auth/issues/2
> .

## 

---

Nate Good
Director of Software Engineering
ShowClix, Inc.

Ph: 412.259.5869
Fax: 724.261.5332
http://www.showclix.com

**Comment by coolaj86** [comment]
Did this get done?
